"""
Django settings for MyDjangoSite project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os, sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.realpath(os.path.dirname(__file__))
sys.path.insert(0, os.path.join(PROJECT_ROOT, os.pardir))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!^4pdxlc2)v)(upz3981rve6vwjv-t6lyq-ms098%vv_2%a_%-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = True
ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'user',
)
ugettext = lambda s: s

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'MyDjangoSite.urls'
AUTH_USER_MODEL = 'user.Account'

LOGIN_URL = "/signin"
LOGIN_REDIRECT_URL = "/"

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
    os.path.join(PROJECT_ROOT, "templates"),
    os.path.join(BASE_DIR, "user/templates"),
    os.path.join(BASE_DIR, "polls/templates"),
)

TEMPLATE_LOADERS = (
    (
        'django.template.loaders.cached.Loader',
        (
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        )
    ),
)

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
    'django.core.context_processors.static',
    'django.contrib.messages.context_processors.messages',
    "django.contrib.auth.context_processors.auth",)

WSGI_APPLICATION = 'MyDjangoSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',

        'NAME': 'learn_site_1',  # Or path to database file if using sqlite3.

        'USER': 'root',  # Not used with sqlite3.

        'PASSWORD': '',  # Not used with sqlite3.

        'HOST': 'localhost',  # Set to sempty string for localhost. Not used with sqlite3.

        'PORT': '',  # Set to empty string for default. Not used with sqlite3.

        # 'CONN_MAX_AGE': 1*24*60*60,

        'OPTIONS': {

            # 'init_command': 'SET storage_engine=INNODB;SET GLOBAL  TRANSACTION ISOLATION LEVEL READ COMMITTED;SET autocommit=1;',

        },
    }
}

AUTHENTICATION_BACKENDS = ('user.backends.MyBackends',
                           # 'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh_cn'
LANGUAGES = [
    ('en', ugettext('English')),
    ('zh-cn', ugettext('Chinese')),
]
TRANSMETA_DEFAULT_LANGUAGE = 'zh-cn',

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = ''

STATICFILES_DIRS = (os.path.join(PROJECT_ROOT, 'static'),)

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
