id=account_dict.get('id'),
nickname=account_dict.get('nickname'),
avatar=account_dict.get('avatar'),
title=account_dict.get('title'),
price=account_dict.get('price'),
answers_count=account_dict.get('answers_count'),
questions_count=account_dict.get('questions_count'),
status=account_dict.get('status'),
income=account_dict.get('income'),
openid=account_dict.get('openid'),
app_openid=account_dict.get('app_openid'),
gravity=account_dict.get('gravity'),
is_admin=account_dict.get('is_admin'),



"questions_count": account.questions_count,
"answers_count": account.answers_count,
／／"followers_count": account.followers_count,
"income": account.income,
"price": account.price,
"nickname": account.nickname,
"id": account.id,
"avatar": account.avatar,
"title": account.title,
／／"introduction": account.introduction,
／／"is_verified": account.is_verified,
／／"is_followed": account.is_followed,