SELECT 
anon_?.question_id AS anon_?_question_id, 
anon_?.question_offer AS anon_?_question_offer, 
anon_?.question_content AS anon_?_question_content, 
anon_?.question_account_id AS anon_?_question_account_id, 
anon_?.question_respondent_id AS anon_?_question_respondent_id, 
anon_?.question_order_score AS anon_?_question_order_score, 
anon_?.question_score AS anon_?_question_score, 
anon_?.question_visitor_count AS anon_?_question_visitor_count, 
anon_?.question_ip AS anon_?_question_ip, 
anon_?.question__visitor_count AS anon_?_question__visitor_count, 
anon_?.question_is_public AS anon_?_question_is_public, 
anon_?.question_is_hidden AS anon_?_question_is_hidden, 
anon_?.question_is_sticky AS anon_?_question_is_sticky, 
anon_?.question_is_recommended AS anon_?_question_is_recommended, 
anon_?.question_status AS anon_?_question_status, 
anon_?.question_review_status AS anon_?_question_review_status, 
anon_?.question_type AS anon_?_question_type, 
anon_?.question_date_created AS anon_?_question_date_created, 
anon_?.question_date_updated AS anon_?_question_date_updated, 

account_?.id AS account_?_id, 
account_?.date_created AS account_?_date_created, 
account_?.unikey AS account_?_unikey, 
account_?.nickname AS account_?_nickname, 
account_?.realname AS account_?_realname, 
account_?._avatar AS account_?__avatar, 
account_?.title AS account_?_title, 
account_?._price AS account_?__price, 
account_?.introduction AS account_?_introduction, 
account_?.order_score AS account_?_order_score, 
account_?.answers_count AS account_?_answers_count, 
account_?.questions_count AS account_?_questions_count, 
account_?.status AS account_?_status, 
account_?.is_star AS account_?_is_star, 
account_?.is_admin AS account_?_is_admin, 
account_?.date_updated AS account_?_date_updated, 
account_?.id AS account_?_id, 
account_?.date_created AS account_?_date_created, 
account_?.unikey AS account_?_unikey, 
account_?.nickname AS account_?_nickname, 
account_?.realname AS account_?_realname, 
account_?._avatar AS account_?__avatar, 
account_?.title AS account_?_title, 
account_?._price AS account_?__price, 
account_?.introduction AS account_?_introduction, 
account_?.order_score AS account_?_order_score, 
account_?.answers_count AS account_?_answers_count, 
account_?.questions_count AS account_?_questions_count, 
account_?.status AS account_?_status, 
account_?.is_star AS account_?_is_star, 
account_?.is_admin AS account_?_is_admin, 
account_?.date_updated AS account_?_date_updated, 

answer_?.id AS answer_?_id, 
answer_?.ip AS answer_?_ip, 
answer_?.question_id AS answer_?_question_id, 
answer_?.status AS answer_?_status, 
answer_?.type AS answer_?_type, 
answer_?.content AS answer_?_content, 
answer_?.is_reanswered AS answer_?_is_reanswered, 
answer_?.date_updated AS answer_?_date_updated, 
answer_?.date_created AS answer_?_date_created, 
answer_?.media_id AS answer_?_media_id, 
answer_?.store_type AS answer_?_store_type, 
answer_?.source AS answer_?_source, 
answer_?.discussion_id AS answer_?_discussion_id   

FROM (

SELECT 
question.id AS question_id, 
question.offer AS question_offer, 
question.content AS question_content, 
question.account_id AS question_account_id, 
question.respondent_id AS question_respondent_id, 
question.order_score AS question_order_score, 
question.score AS question_score, 
question.visitor_count AS question_visitor_count, 
question.ip AS question_ip, 
question._visitor_count AS question__visitor_count, 
question.is_public AS question_is_public, 
question.is_hidden AS question_is_hidden, 
question.is_sticky AS question_is_sticky, 
question.is_recommended AS question_is_recommended, 
question.status AS question_status, 
question.review_status AS question_review_status, 
question.type AS question_type, 
question.date_created AS question_date_created, 
question.date_updated AS question_date_updated   
FROM question  
WHERE question.status = ? AND 
question.is_public = TRUE AND 
question.is_hidden = FALSE AND 
question.respondent_id IN (?)
ORDER BY question.date_updated DESC
LIMIT ? OFFSET ?) AS anon_?
LEFT OUTER JOIN account AS account_?ON anon_?.question_account_id = account_?.id
LEFT OUTER JOIN account AS account_? ON anon_?.question_respondent_id = account_?.id
LEFT OUTER JOIN answer AS answer_? ON anon_?.question_id = answer_?.question_id

ORDER BY anon_?.question_date_updated DESC


SELECT anon_?.question_id AS anon_?_question_id,  
anon_?.question_offer AS anon_?_question_offer,  
anon_?.question_content AS anon_?_question_content,  
anon_?.question_account_id AS anon_?_question_account_id,  
anon_?.question_respondent_id AS anon_?_question_respondent_id,  
anon_?.question_order_score AS anon_?_question_order_score,  
anon_?.question_score AS anon_?_question_score,  
anon_?.question_visitor_count AS anon_?_question_visitor_count,  
anon_?.question_ip AS anon_?_question_ip,  
anon_?.question__visitor_count AS anon_?_question__visitor_count,  
anon_?.question_is_public AS anon_?_question_is_public,  
anon_?.question_is_hidden AS anon_?_question_is_hidden,  
anon_?.question_is_sticky AS anon_?_question_is_sticky,  
anon_?.question_is_recommended AS anon_?_question_is_recommended,  
anon_?.question_status AS anon_?_question_status,  
anon_?.question_review_status AS anon_?_question_review_status,  
anon_?.question_type AS anon_?_question_type,  
anon_?.question_date_created AS anon_?_question_date_created,  
anon_?.question_date_updated AS anon_?_question_date_updated,  
account_?.id AS account_?_id,  
account_?.date_created AS account_?_date_created,  
account_?.unikey AS account_?_unikey,  
account_?.nickname AS account_?_nickname,  
account_?.realname AS account_?_realname,  
account_?._avatar AS account_?__avatar,  
account_?.title AS account_?_title,  
account_?._price AS account_?__price,  
account_?.introduction AS account_?_introduction,  
account_?.order_score AS account_?_order_score,  
account_?.answers_count AS account_?_answers_count,  
account_?.questions_count AS account_?_questions_count,  
account_?.status AS account_?_status,  
account_?.is_star AS account_?_is_star,  
account_?.is_admin AS account_?_is_admin,  
account_?.date_updated AS account_?_date_updated,  
account_?.id AS account_?_id,  
account_?.date_created AS account_?_date_created,  
account_?.unikey AS account_?_unikey,  
account_?.nickname AS account_?_nickname,  
account_?.realname AS account_?_realname,  
account_?._avatar AS account_?__avatar,  
account_?.title AS account_?_title,  
account_?._price AS account_?__price,  
account_?.introduction AS account_?_introduction,  
account_?.order_score AS account_?_order_score,  
account_?.answers_count AS account_?_answers_count,  
account_?.questions_count AS account_?_questions_count,  
account_?.status AS account_?_status,  
account_?.is_star AS account_?_is_star,  
account_?.is_admin AS account_?_is_admin,  
account_?.date_updated AS account_?_date_updated,  
answer_?.id AS answer_?_id,  
answer_?.ip AS answer_?_ip,  
answer_?.question_id AS answer_?_question_id,  
answer_?.status AS answer_?_status,  
answer_?.type AS answer_?_type,  
answer_?.content AS answer_?_content,  
answer_?.is_reanswered AS answer_?_is_reanswered,  
answer_?.date_updated AS answer_?_date_updated,  
answer_?.date_created AS answer_?_date_created,  
answer_?.media_id AS answer_?_media_id,  
answer_?.store_type AS answer_?_store_type,  
answer_?.source AS answer_?_source,  
answer_?.discussion_id AS answer_?_discussion_id   
FROM (SELECT question.id AS question_id,  
question.offer AS question_offer,  
question.content AS question_content,  
question.account_id AS question_account_id,  
question.respondent_id AS question_respondent_id,  
question.order_score AS question_order_score,  
question.score AS question_score,  
question.visitor_count AS question_visitor_count,  
question.ip AS question_ip,  
question._visitor_count AS question__visitor_count,  
question.is_public AS question_is_public,  
question.is_hidden AS question_is_hidden,  
question.is_sticky AS question_is_sticky,  
question.is_recommended AS question_is_recommended,  
question.status AS question_status,  
question.review_status AS question_review_status,  
question.type AS question_type,  
question.date_created AS question_date_created,  
question.date_updated AS question_date_updated   
FROM question   WHERE question.status = ? 
AND question.is_public = true 
AND question.is_hidden = false 
AND question.respondent_id = ? 
AND question.review_status IN (?,  
?) 
AND question.date_updated <= ?::timestamptz 
ORDER BY question.score DESC 
   LIMIT ? OFFSET ?) 
AS anon_? 
LEFT OUTER JOIN account AS account_? ON anon_?.question_account_id = account_?.id 
LEFT OUTER JOIN account AS account_? ON anon_?.question_respondent_id = account_?.id 
LEFT OUTER JOIN answer AS answer_? ON anon_?.question_id = answer_?.question_id 
ORDER BY anon_?.question_score DESC


SELECT anon_?.question_id AS anon_?_question_id,  
anon_?.question_offer AS anon_?_question_offer,  
anon_?.question_content AS anon_?_question_content,  
anon_?.question_account_id AS anon_?_question_account_id,  
anon_?.question_respondent_id AS anon_?_question_respondent_id,  
anon_?.question_order_score AS anon_?_question_order_score,  
anon_?.question_score AS anon_?_question_score,  
anon_?.question_visitor_count AS anon_?_question_visitor_count,  
anon_?.question_ip AS anon_?_question_ip,  
anon_?.question__visitor_count AS anon_?_question__visitor_count,  
anon_?.question_is_public AS anon_?_question_is_public,  
anon_?.question_is_hidden AS anon_?_question_is_hidden,  
anon_?.question_is_sticky AS anon_?_question_is_sticky,  
anon_?.question_is_recommended AS anon_?_question_is_recommended,  
anon_?.question_status AS anon_?_question_status,  
anon_?.question_review_status AS anon_?_question_review_status,  
anon_?.question_type AS anon_?_question_type,  
anon_?.question_date_created AS anon_?_question_date_created,  
anon_?.question_date_updated AS anon_?_question_date_updated,  
account_?.id AS account_?_id,  
account_?.date_created AS account_?_date_created,  
account_?.unikey AS account_?_unikey,  
account_?.nickname AS account_?_nickname,  
account_?.realname AS account_?_realname,  
account_?._avatar AS account_?__avatar,  
account_?.title AS account_?_title,  
account_?._price AS account_?__price,  
account_?.introduction AS account_?_introduction,  
account_?.order_score AS account_?_order_score,  
account_?.answers_count AS account_?_answers_count,  
account_?.questions_count AS account_?_questions_count,  
account_?.status AS account_?_status,  
account_?.is_star AS account_?_is_star,  
account_?.is_admin AS account_?_is_admin,  
account_?.date_updated AS account_?_date_updated,  
account_?.id AS account_?_id,  
account_?.date_created AS account_?_date_created,  
account_?.unikey AS account_?_unikey,  
account_?.nickname AS account_?_nickname,  
account_?.realname AS account_?_realname,  
account_?._avatar AS account_?__avatar,  
account_?.title AS account_?_title,  
account_?._price AS account_?__price,  
account_?.introduction AS account_?_introduction,  
account_?.order_score AS account_?_order_score,  
account_?.answers_count AS account_?_answers_count,  
account_?.questions_count AS account_?_questions_count,  
account_?.status AS account_?_status,  
account_?.is_star AS account_?_is_star,  
account_?.is_admin AS account_?_is_admin,  
account_?.date_updated AS account_?_date_updated,  
answer_?.id AS answer_?_id,  
answer_?.ip AS answer_?_ip,  
answer_?.question_id AS answer_?_question_id,  
answer_?.status AS answer_?_status,  
answer_?.type AS answer_?_type,  
answer_?.content AS answer_?_content,  
answer_?.is_reanswered AS answer_?_is_reanswered,  
answer_?.date_updated AS answer_?_date_updated,  
answer_?.date_created AS answer_?_date_created,  
answer_?.media_id AS answer_?_media_id,  
answer_?.store_type AS answer_?_store_type,  
answer_?.source AS answer_?_source,  
answer_?.discussion_id AS answer_?_discussion_id   
FROM (SELECT question.id AS question_id,  
question.offer AS question_offer,  
question.content AS question_content,  
question.account_id AS question_account_id,  
question.respondent_id AS question_respondent_id,  
question.order_score AS question_order_score,  
question.score AS question_score,  
question.visitor_count AS question_visitor_count,  
question.ip AS question_ip,  
question._visitor_count AS question__visitor_count,  
question.is_public AS question_is_public,  
question.is_hidden AS question_is_hidden,  
question.is_sticky AS question_is_sticky,  
question.is_recommended AS question_is_recommended,  
question.status AS question_status,  
question.review_status AS question_review_status,  
question.type AS question_type,  
question.date_created AS question_date_created,  
question.date_updated AS question_date_updated   
FROM question,  
tenant_question
WHERE question.is_hidden IS false
AND question.is_public IS true 
AND question.status = ? 
AND question.date_updated <= ?::timestamptz 
AND tenant_question.question_id = question.id 
AND tenant_question.status = ? 
AND tenant_question.tenant_id = ? 
ORDER BY question.date_updated DESC    LIMIT ? OFFSET ?) AS anon_? 
LEFT OUTER JOIN account AS account_? ON anon_?.question_account_id = account_?.id 
LEFT OUTER JOIN account AS account_? ON anon_?.question_respondent_id = account_?.id 
LEFT OUTER JOIN answer AS answer_? ON anon_?.question_id = answer_?.question_id 
ORDER BY anon_?.question_date_updated DESC 
